[package]
name = "level_7_bevy_breakout"
version = "0.1.0"
authors = ["Damien Plumettaz <damien.plumettaz@bluewin.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.5"
bevy-inspector-egui = "0.6.1"